### ISSUE TITLE
Tips:FileNotFoundError

### ISSUE THREAD

**Issue by NewSun55** [bchimagine/fetal-brain-segmentation#1]
Tips information:
`Traceback (most recent call last):
  File "E:/deep_learn_code/15FBSM/fetal-brain-segmentation-main/code/train.py", line 86, in <module>
    X_train = np.load("../data/X_train.npy", mmap_mode="r")
  File "F:\other_ana\15FBSM\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../data/X_train.npy'`

Hello, you can provide documents with x_train.npy and y_train.npy.

**Comment by NewSun55** [comment]
Sorry, the documents mentioned above can be obtained through this create_dataset.py.

**Comment by TaherehSharifian** [comment]
> Sorry, the documents mentioned above can be obtained through this create_dataset.py.

Hello, I have problems loading the data.
I ran `create_dataset_ and it gives me a file like this.
![image](https://user-images.githubusercontent.com/91904415/235306554-a6bd853a-ae6d-4b90-97a1-8dfea4230937.png)


is this correct? 
and also, there are no files by these names in the repo.
![image](https://user-images.githubusercontent.com/91904415/235306539-dec1f0d1-119b-4ab3-a93f-43db54d6171c.png)

what should I do? did you fix it?
